### ISSUE TITLE
Fails to setup (can't add Tapo)

### ISSUE THREAD

**Issue by samwise22** [petretiandrea/home-assistant-tapo-p100#148]
Using v 1.2.9

After installing via HACS and performing a HA restart I'm unable to install Tapo via the HA integrations page. The logs after restart show the following.

Log Details (ERROR)
Logger: homeassistant.components.switch
Source: helpers/update_coordinator.py:161
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 17:32:35 (4 occurrences)
Last logged: 17:32:35

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 224, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 84, in login
    await self._login_request(self.username, self.password)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 166, in _login_request
    logger.debug(f"Will login using username '{username[5:]}...'")
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

**Comment by kerozoli** [comment]
I think this issue is related to Home Assistant 2022.3
I downgraded my server to Home Assistant 2022.2.9 and the issue is gone

**Comment by kerozoli** [comment]
Isn't this issue related to Home Assistant 2022.3 ?

**Comment by kerozoli** [comment]
Sorry for my previous comment/delete comment :)

I tested my tapo integration with home assistant 2022.2.9 and 2022.3.1 (with ~ 6 bulbs and 8 switches)
The integration works perfectly with 2022.2.9 but failed to initialize with 2022.3.1

So I think this issue is related to the new 2022.3 version
Thanks

**Comment by petretiandrea** [comment]
> Using v 1.2.9
> 
> After installing via HACS and performing a HA restart I'm unable to install Tapo via the HA integrations page. The logs after restart show the following.
> 
> Log Details (ERROR) Logger: homeassistant.components.switch Source: helpers/update_coordinator.py:161 Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22)) First occurred: 17:32:35 (4 occurrences) Last logged: 17:32:35
> 
> Error while setting up tapo platform for switch Traceback (most recent call last): File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback return await self.api.get_state() File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state state=await self.get_state_as_dict(), File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict return await self._execute_method_request(device_info_method) File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 224, in _execute_method_request dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method)) AttributeError: 'NoneType' object has no attribute 'encrypt'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data return await self._update_with_fallback() File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback await self.api.login() File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 84, in login await self._login_request(self.username, self.password) File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 166, in _login_request logger.debug(f"Will login using username '{username[5:]}...'") TypeError: 'NoneType' object is not subscriptable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data raise UpdateFailed() from exception homeassistant.helpers.update_coordinator.UpdateFailed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform coordinator = await setup_tapo_coordinator_from_dictionary(hass, config) File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary return await setup_tapo_coordinator( File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh raise ex homeassistant.exceptions.ConfigEntryNotReady

Try to remove and install again. Seems an error related to wrong config entry, have you a set a device in `configuration.yaml` before installing the integration and restarting? Or have you add a device via UI?

**Comment by tlamoureux24** [comment]
Hello,

Same for me
Using v 1.2.9 with HAOS 2022.3.2

Install via HACS and perform a HA restart (and a full reboot in case of), unable to find Tapo via the HA integrations page for install.

**Comment by kerozoli** [comment]
I tried to update my HAOS to 2022.3.3 again but I got the same error(for existing setup) , not sure if it's related to this issue or not :

`Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 8:56:18 AM (3 occurrences)
Last logged: 8:58:07 AM

Unable to install package plugp100==2.1.13b1: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [30 lines of output] Testing support for clang Target does not support clang Testing support for gcc Target does not support gcc Testing support for stdint.h header Target does not support stdint.h header Testing support for 128-bit integer Target does not support 128-bit integer Testing support for cpuid.h header Target does not support cpuid.h header Testing support for intrin.h header Target does not support intrin.h header Testing support for posix_memalign Target does not support posix_memalign Testing support for memalign Target does not support memalign Testing support for SSE2(intrin.h) Target does not support SSE2(intrin.h) Testing support for SSE2(x86intrin.h) Target does not support SSE2(x86intrin.h) Testing support for SSE2(emmintrin.h) Target does not support SSE2(emmintrin.h) Warning: compiler does not support AESNI instructions Warning: compiler does not support CLMUL instructions running bdist_wheel running build running build_py running build_ext building 'Crypto.Hash._MD2' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pycryptodome error: subprocess-exited-with-error × Running setup.py install for pycryptodome did not run successfully. │ exit code: 1 ╰─> [32 lines of output] Testing support for clang Target does not support clang Testing support for gcc Target does not support gcc Testing support for stdint.h header Target does not support stdint.h header Testing support for 128-bit integer Target does not support 128-bit integer Testing support for cpuid.h header Target does not support cpuid.h header Testing support for intrin.h header Target does not support intrin.h header Testing support for posix_memalign Target does not support posix_memalign Testing support for memalign Target does not support memalign Testing support for SSE2(intrin.h) Target does not support SSE2(intrin.h) Testing support for SSE2(x86intrin.h) Target does not support SSE2(x86intrin.h) Testing support for SSE2(emmintrin.h) Target does not support SSE2(emmintrin.h) Warning: compiler does not support AESNI instructions Warning: compiler does not support CLMUL instructions running install /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py running build_ext building 'Crypto.Hash._MD2' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. WARNING: No metadata found in /usr/local/lib/python3.9/site-packages error: legacy-install-failure × Encountered error while trying to install package. ╰─> pycryptodome note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.1.13b1'].
8:58:07 AM – (ERROR) setup.py`

**Comment by tricoos** [comment]
After removing and reinstalling it it appeared for me as well.
