### ISSUE TITLE
Integration doesn't load anymore: cannot import name 'TapoApiClientConfig' from 'plugp100'

### ISSUE THREAD

**Issue by lamarios** [petretiandrea/home-assistant-tapo-p100#408]
## Version of the integration
1.6.1

## Configuration

Devices set up via the UI. 

## Describe the bug

The integration used to work fine after some general updates (home-assistant, hacs and tapo integration) it stopped working.

I tried re-installing the integration but I'm still facing the same issue.

## Debug log

```text

ImportError: cannot import name 'TapoApiClientConfig' from 'plugp100' (/config/deps/lib/python3.10/site-packages/plugp100/__init__.py)
2023-05-25 11:40:31.555 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1072, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 578, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo/__init__.py", line 8, in <module>
    from custom_components.tapo.common_setup import (
  File "/config/custom_components/tapo/common_setup.py", line 6, in <module>
    from plugp100 import (
ImportError: cannot import name 'TapoApiClientConfig' from 'plugp100' (/config/deps/lib/python3.10/site-packages/plugp100/__init__.py)


```

**Comment by daloki83** [comment]
Had the same problem today....
-remove integration from devices
-removed integration from HACS
-Full restart of HA
-reinstall with HACS
-adding and configuring in integrations
=working again

**Comment by lamarios** [comment]
I just tried that but i'm still facing the same problem

**Comment by SkoobyDu** [comment]
Hi, I'm facing the same issue since updating to 2023.06.02.

Had to roll back to previous backup.

Error

[2023-06-19 21:31](calendar:T7:2023-06-19 21:31):19.456 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration tapo: Unable to import component: cannot import name 'TapoApiClient' from 'plugp100' (/usr/local/lib/python3.11/site-packages/plugp100/__init__.py)

**Comment by petretiandrea** [comment]
Try latest 1.7.0
