### ISSUE TITLE
Integration doesn't work with Home Assistant 2022.9.2

### ISSUE THREAD

**Issue by damiano75** [petretiandrea/home-assistant-tapo-p100#243]
## Version of the custom_component

v1.2.15

## Configuration

Added using UI

![image](https://user-images.githubusercontent.com/47896789/189605048-5f574d42-1c0c-47e8-b94e-ea9e20265eb6.png)

```yaml

2022-09-12 09:16:00.772 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tapo
2022-09-12 09:16:00.785 INFO (MainThread) [homeassistant.components.light] Setting up light.tapo
2022-09-12 09:16:00.813 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tapo
2022-09-12 09:16:00.822 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.tapo
2022-09-12 09:16:00.848 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/switch.py", line 19, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/switch.py", line 33, in _setup_from_coordinator
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
2022-09-12 09:16:00.860 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/light.py", line 34, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/light.py", line 49, in _setup_from_coordinator
if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model'
2022-09-12 09:16:00.885 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/sensor.py", line 31, in async_setup_entry
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
AttributeError: 'NoneType' object has no attribute 'model'
2022-09-12 09:16:00.964 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for iPhone di Damiano: 7 sent, 500 allowed, 0 errors, resets in 16:43:59
2022-09-12 09:16:04.227 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform tapo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/tapo/tapo_sensor_entity.py", line 43, in unique_id
return super().unique_id + "_" + self.sensor_config.name.replace(" ", "_")
File "/config/custom_components/tapo/tapo_entity.py", line 29, in unique_id
return self.coordinator.data.device_id
AttributeError: 'NoneType' object has no attribute 'device_id'
2022-09-12 09:16:04.303 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/tapo/tapo_sensor_entity.py", line 43, in unique_id
return super().unique_id + "_" + self.sensor_config.name.replace(" ", "_")
File "/config/custom_components/tapo/tapo_entity.py", line 29, in unique_id
return self.coordinator.data.device_id

```

## Describe the bug

After upgrading to Home Assistant 2022.9.2 the integration doesn't work

## Debug log

```text



```

**Comment by loryanstrant** [comment]
Oh this is good to know, I literally just upgraded to 2022.9.2 a couple of hours ago and was starting to troubleshoot why 3 of my devices (all Tapo units) weren't coming back online.

**Comment by Pka78** [comment]
+1 Same issue with 2022.9.3.

**Comment by petretiandrea** [comment]
Can you report the OS info and Hardware Info?

**Comment by loryanstrant** [comment]
I'm running HAOS in a VM on a Synology DS920+ NAS.
My Tapo devices:
2 x - L920 (firmware 1.0.9 Build 220422 Rel.150004)
1 x - L530 (firmware 1.2.2 Build 20220110 Rel.72329)

**Comment by GoliathLabs** [comment]
```
2022-09-14 14:22:31.326 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/switch.py", line 19, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/switch.py", line 33, in _setup_from_coordinator
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
2022-09-14 14:22:31.327 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/light.py", line 34, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/light.py", line 49, in _setup_from_coordinator
if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model'
2022-09-14 14:22:31.328 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/sensor.py", line 31, in async_setup_entry
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by Lockie85** [comment]
Hey,

Does this issue relate to why my previously working L510 Series appears to have stopped working recently since updating HA.

It seems to simply state:
Retrying setup: None

**Comment by petretiandrea** [comment]
CPU architecture?

**Comment by loryanstrant** [comment]
> CPU architecture?
> 

Of the VM, or the NAS?
My DS920 has an Intel Celeron J4125.

**Comment by petretiandrea** [comment]
> > CPU architecture?
> 
> Of the VM, or the NAS? My DS920 has an Intel Celeron J4125.

Are you running vm using ARM cpu architecture?

**Comment by hesnuks** [comment]
Same Problem with Raspberry Pi 4.

**Comment by mamoel666** [comment]
With my NUC 11 Pro (NUC11TNHi3, Core i3-1115G4), Ubuntu 22.04.01 and Home Assistant 2022.9.4 (Docker), the integration doesn't work at all.
I add it via HACS, do a restart, but can't find anything with 'Tapo' under 'integrations'.

**Comment by hesnuks** [comment]
> With my NUC 11 Pro (NUC11TNHi3, Core i3-1115G4), Ubuntu 22.04.01 and Home Assistant 2022.9.4 (Docker), the integration doesn't work at all. I add it via HACS, do a restart, but can't find anything with 'Tapo' under 'integrations'.

Did you clear the Cache with Shift + F5?

**Comment by mamoel666** [comment]
> Did you clear the Cache with Shift + F5?

Oh man...it seems I did not!
I just repeated the whole procedure and now I see my Tapo P110 in HA including the energy monitoring. No warnings or errors in the logs.
Sorry!

So at least this works with my installation of Home Assistant 2022.9.4.

**Comment by damiano75** [comment]
After the upgrade to Home Assistant 2022.9.4 the issue is fixed for me...

**Comment by loryanstrant** [comment]
> After the upgrade to Home Assistant 2022.9.4 the issue is fixed for me...

Do you mean after the update in HACS that just came through today, or since upgrading to 2022.9.4 it works whereas previous 2022.9.x versions didn't?

**Comment by damiano75** [comment]
> > After the upgrade to Home Assistant 2022.9.4 the issue is fixed for me...
> 
> Do you mean after the update in HACS that just came through today, or since upgrading to 2022.9.4 it works whereas previous 2022.9.x versions didn't?

Just upgrading to Home Assistant 2022.9.4, I did the upgrade yesterday and tapo p100 was online again

**Comment by hesnuks** [comment]
On Updating to 2022.9.4 for me 2 of my plugs were not available anymore. 2 of the Plugs were available...

**Comment by loryanstrant** [comment]
@hesnuks are the 4 plugs different models, or the same?

**Comment by hesnuks** [comment]
@loryanstrant all the same. P100 and all are on the newest version.

**Comment by loryanstrant** [comment]
Well, that's confusing. I might try to upgrade mine to 2022.9.4 tomorrow and see if it makes a difference.
The only affected lights are the ones in my kids rooms, and they've gone to sleep.
This is making a stronger case for me to switch over any proprietary things like these to something like ESPHome where possible, because @petretiandrea doesn't exactly have to deliver to a SLA - but I do for my kids. :-)

**Comment by hesnuks** [comment]
I just readded them also in the Tapo App and then readded them in the integration. Now it works again. So it seems to work in 2022.9.4 but with some extra work :)

**Comment by GoliathLabs** [comment]
After adding them in HomeAssistant 2022.9.4 they are available again

**Comment by Pka78** [comment]
> After adding them in HomeAssistant 2022.9.4 they are available again

+1, after updating 2022.9.4 Plugin works again.

**Comment by loryanstrant** [comment]
Also confirmed as working. Updated to 2022.9.4, removed integration, rebooted, re-added, all fine.

**Comment by stain3565** [comment]
2022.9.7 has caused the issue for me. Last few versions seemed OK but now every one of my p100 and p110 plugs is unavailable. Seems each new HA version is a bit hit and miss as to whether the Tapo integration works.

In logs:

Logger: homeassistant.config_entries
Source: config_entries.py:1034
First occurred: 00:13:32 (2 occurrences)
Last logged: 00:15:08

Config entry 'Tapo 9' for tapo integration not ready yet: None; Retrying in background

Config entry 'Tapo 12' for tapo integration not ready yet: None; Retrying in background


Same for every plug

**Comment by mamoel666** [comment]
No problems here with 2022.9.7 with one p110 plug.

**Comment by shocker2** [comment]
Works fine on 2022.9.7 with 23 P110 plugs and 5 P115.

**Comment by stain3565** [comment]
OK. Well mine is definitely not working now. I have had a go at removing all Tapo Controller entities and adding from scratch.

Getting invalid authentication for every one.

The id and password have not changed (lower case letters and numbers for the password). The ip addresses I am adding as the host match each plug ip address in Tapo app device info.

It was working until either version 6 or 7.

I thought that it could have been due to renaming tapo devices/entities in HA. However, the failure to add them from scratch suggests otherwise, as they are nit even getting past validation. No logs for adding new devices but before, that, I was getting the "config entry xxxx for tapo integration not ready yet".

I hope I don't have to re-pair all 18 in the Tapo app but, unless others get similar issues, I may have to.

**Comment by vscmail** [comment]
Hello running 2022.6.7 on Pi4, I installed the add-on (Result ok) the when I try to configure a new Tapo 100 I always get this error:
Logger: homeassistant.components.switch
Source: helpers/update_coordinator.py:178
Integration: Switch (documentation, issues)

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 89, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 213, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 225, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 85, in login
    await self._login_request(self.username, self.password)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 209, in _login_request
    self.token = decrypted_inner_response['result']['token']
KeyError: 'result'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

When I try to connect a device it always gives me the feedback
Invalid authentication.
Reading the previous post from stain3565, I kind of understand that not only the email shall be all small caps (that's OK) but also that the password shall be only using combination of small caps and figures. So I did it.
Anything else I can do to fix this issue?
Thanks

**Comment by stain3565** [comment]
I went back to 2022.9.4, removed all plugs from the tapo app and home assistant, re-added in tapo app and integrated again in home assistant. 

My one thought during this was perhaps my plug firmware was not up to date. I know that some P100s were older firmware but the P110s were up to date.

So now all readded and latest firmware.

First time in, looked OK with no exclamation marks against any online plugs.

However, it is now haphazard as to which plugs are available in HA after any restart. Sadly today the number is just 2 out of 20.
And one of those I just readded from scratch.

Log for one attempted reload is below:

Logger: homeassistant.config_entries
Source: config_entries.py:1031
First occurred: 16:08:58 (1 occurrences)
Last logged: 16:08:58

Config entry 'Tapo 10' for tapo integration not ready yet: None; Retrying in background


I have also tried in 2022.9.7 but results were the same.

**Comment by petretiandrea** [comment]
I will close this issue cause 2022.9.x is now working. So if you have problem with 2022.10.x open another issue instead of writing here.

I would like to remind you that integration works with devices which have a static IP, so if not please setup it from router page.
